nodeLinker: node-modules

logFilters:
    # MISSING_PEER_DEPENDENCY
    - code: YN0002
      level: discard
    # FETCH_NOT_CACHED
    - code: YN0013
      level: discard
    # NODE_GYP_INJECTED
    - code: YN0032
      level: discard
    # INCOMPATIBLE_PEER_DEPENDENCY
    - code: YN0060
      level: discard

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.0.cjs
